
- name: configure ec2 instance to be jenkins slave
  hosts: all
  tasks:
    - name: update packages
      apt:
        name: "*"
        state: latest
        
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install docker-ce
      apt:
        name: docker-ce
        state: latest

    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker
        
    - name: install openjdk 
      apt:
        name: "{{item}}"
        state: present
      loop:
        - openjdk-11-jdk
        
    - name: make sure that shh and openjdk are running
      service:
        name: "{{item}}"
        state: started
        enabled: true
      loop:
        - openjdk-11-jdk
        - sshd
        
    - name: create jenkins home directory
      file:
        path: /home/ubuntu/jenkins
        state: Directory
    
